Paths:
  mesh_dir: /Data/LaNau_V3/Train
  texture_dir: /Data/LaNau_V3/Train_texture
  val_mesh_dir: /Data/LaNau_V3/Val
  val_texture_dir: /Data/LaNau_V3/Val_texture
  ignore_index: -1
  log_dir: /Data/LaNau_V3/log
  checkpoint_dir: /Data/LaNau_V3/Training_Results
training:
  epochs: 200
  batch_size: 1
  clusters_per_batch: 10
  weight_decay: 0.1
  learning_rate: 0.0001
model:
  embedding_dim: 64
  num_heads: 1
  num_attention_blocks: 4
  n_classes: 8
  n_clusters : 300
  dropout : 0.1
augmentation:  # New section for augmentation settings
  rotation_range: 45
  scale_range: 2
  noise_std: 0.01
  flip_probability: 0.5

  
