paths:
  mesh_dir: /bigwork/nhgnheid/EU_data_V3/Train
  json_dir : /bigwork/nhgnheid/H3D_orderdL/face_feature_val
  texture_dir : /bigwork/nhgnheid/EU_data_V3/Train_texture
  log_dir: /bigwork/nhgnheid/log_nomeformer/log1-7
  checkpoint_dir: /bigwork/nhgnheid/CVPR_2026_EX/EU_V3/Ex_7
  val_mesh_dir: /bigwork/nhgnheid/EU_data_V3/Val
  val_json_dir : /bigwork/nhgnheid/H3D_orderdL/face_feature_val
  val_texture_dir : /bigwork/nhgnheid/EU_data_V3/Train_texture
  ignore_index: -1
training:
  epochs: 200
  batch_size: 1
  clusters_per_batch: 10
  weight_decay: 0.1
  learning_rate: 0.0001
model:
  embedding_dim: 64
  num_heads: 1
  num_attention_blocks: 4
  n_classes: 8
  n_clusters : 300
  dropout : 0.1
augmentation:  # New section for augmentation settings
  rotation_range: 45
  scale_range: 2
  noise_std: 0.01
  flip_probability: 0.5

  