paths:
  mesh_dir: /Data/LaNau_V3/Test
  texture_dir: /Data/LaNau_V3/Test_texture
  ignore_index: -1
  checkpoint_dir: /Data/LaNau_V3/Training_Results
  prediction_out_path: /Data/LaNau_V3/Output

model:
  feature_dim: 16
  embedding_dim: 64
  num_heads: 1
  num_attention_blocks: 4
  n_classes: 8
  n_clusters: 300
  dropout: 0.0
  clusters_per_batch: 30
  batch_size: 1




